server:
  port: 8081
  servlet:
    context-path: /kafkaNginxShow
spring:
  kafka:
    bootstrap-servers: HadoopNode00:9092,HadoopNode01:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      group-id: Nginx-Kafka-Application
      auto-offset-reset: earliest
      enable-auto-commit: false


